"""Config dataclasses for the mini-PFN demo: prior, model, and training."""

from __future__ import annotations

from dataclasses import dataclass
from enum import Enum


class Augmentation(str, Enum):
    """Missingness augmentation applied to each training batch.

    CELLS: questionnaire-style per-row missingness on all rows (train + test),
    optionally label-informative (MNAR). COLUMNS: whole feature columns NaN'd
    in the test rows only. NONE: only the prior's built-in mild MCAR cells.
    """

    CELLS = "cells"
    COLUMNS = "columns"
    NONE = "none"


@dataclass(kw_only=True)
class PriorConfig:
    """Distribution over synthetic classification tasks (the pretraining prior).

    Each task is generated by a random MLP acting as a small structural causal
    model: shared latent noise is propagated through random layers, some hidden
    nodes become the observed features, and a deep node is quantile-binned into
    the class label.
    """

    min_features: int = 2
    max_features: int = 10
    min_rows: int = 60
    max_rows: int = 160
    min_train_frac: float = 0.3
    max_train_frac: float = 0.8
    min_classes: int = 2
    max_classes: int = 4
    min_noise_dim: int = 2
    max_noise_dim: int = 6
    min_depth: int = 1
    max_depth: int = 3
    min_width: int = 4
    max_width: int = 16
    max_cell_missing_frac: float = 0.1
    discretize_prob: float = 0.2

    def __post_init__(self) -> None:
        if not 1 <= self.min_features <= self.max_features:
            raise ValueError("need 1 <= min_features <= max_features")
        if not 8 <= self.min_rows <= self.max_rows:
            raise ValueError("need 8 <= min_rows <= max_rows")
        if not 0.0 < self.min_train_frac <= self.max_train_frac < 1.0:
            raise ValueError("train fractions must satisfy 0 < min <= max < 1")
        if not 2 <= self.min_classes <= self.max_classes:
            raise ValueError("need 2 <= min_classes <= max_classes")
        if self.min_rows * self.min_train_frac < self.max_classes:
            raise ValueError("min train rows must be able to contain max_classes rows")
        if not 1 <= self.min_depth <= self.max_depth:
            raise ValueError("need 1 <= min_depth <= max_depth")
        if not 1 <= self.min_noise_dim <= self.max_noise_dim:
            raise ValueError("need 1 <= min_noise_dim <= max_noise_dim")
        if not 1 <= self.min_width <= self.max_width:
            raise ValueError("need 1 <= min_width <= max_width")
        if not 0.0 <= self.max_cell_missing_frac < 1.0:
            raise ValueError("max_cell_missing_frac must be in [0, 1)")
        if not 0.0 <= self.discretize_prob <= 1.0:
            raise ValueError("discretize_prob must be in [0, 1]")


@dataclass(kw_only=True)
class ModelConfig:
    """Architecture of the mini-PFN transformer."""

    d_model: int = 128
    n_layers: int = 6
    n_heads: int = 4
    max_classes: int = 4
    feature_emb_dim: int = 32

    def __post_init__(self) -> None:
        if self.d_model % self.n_heads != 0:
            raise ValueError("d_model must be divisible by n_heads")
        if self.n_layers < 1:
            raise ValueError("n_layers must be >= 1")
        if self.max_classes < 2:
            raise ValueError("max_classes must be >= 2")
        if self.feature_emb_dim < 1:
            raise ValueError("feature_emb_dim must be >= 1")


@dataclass(kw_only=True)
class TrainConfig:
    """Pretraining hyperparameters."""

    steps: int = 25_000
    batch_size: int = 32
    lr: float = 3e-4
    warmup_steps: int = 500
    weight_decay: float = 0.01
    grad_clip: float = 1.0
    seed: int = 0
    device: str = "auto"
    log_every: int = 200
    checkpoint_every: int = 2_000
    out_path: str = "checkpoints/minipfn.pt"
    augmentation: Augmentation = Augmentation.CELLS
    cell_missing_task_prob: float = 0.7
    cell_missing_max_rate: float = 0.6
    informative_missing_prob: float = 0.3
    drop_feature_task_prob: float = 0.5
    max_drop_frac: float = 0.5

    def __post_init__(self) -> None:
        self.augmentation = Augmentation(self.augmentation)
        if self.steps < 1:
            raise ValueError("steps must be >= 1")
        if self.batch_size < 1:
            raise ValueError("batch_size must be >= 1")
        if self.lr <= 0:
            raise ValueError("lr must be positive")
        if not 0 <= self.warmup_steps <= self.steps:
            raise ValueError("warmup_steps must be in [0, steps]")
        for name in (
            "cell_missing_task_prob",
            "informative_missing_prob",
            "drop_feature_task_prob",
        ):
            if not 0.0 <= getattr(self, name) <= 1.0:
                raise ValueError(f"{name} must be in [0, 1]")
        if not 0.0 < self.cell_missing_max_rate <= 0.95:
            raise ValueError("cell_missing_max_rate must be in (0, 0.95]")
        if not 0.0 < self.max_drop_frac < 1.0:
            raise ValueError("max_drop_frac must be in (0, 1)")
