"""Synthetic classification-task prior and the test-time feature-dropout corruption.

Each batch of tasks is generated by one random MLP architecture acting as a
small structural causal model: shared latent noise is propagated through
random per-task weights, hidden nodes become the observed features, and a node
of the deepest layer is rank-binned into the class label. This mirrors (at
small scale) the SCM prior TabPFN is pretrained on.
"""

from __future__ import annotations

import math
from dataclasses import dataclass

import torch

from geo_pfn.minipfn.config import PriorConfig

_ACTIVATIONS = (torch.tanh, torch.relu, torch.sin, torch.abs)


@dataclass
class PriorBatch:
    """A batch of synthetic tasks sharing one (rows, features) shape."""

    x: torch.Tensor  # (B, R, F) float32; NaN marks missing cells
    y: torch.Tensor  # (B, R) int64 class labels
    train_size: int  # rows < train_size are context, the rest are queries
    n_classes: torch.Tensor  # (B,) int64 classes per task


def _randint(generator: torch.Generator, low: int, high: int) -> int:
    """Uniform integer in [low, high] inclusive."""
    return int(torch.randint(low, high + 1, (1,), generator=generator).item())


def sample_prior_batch(
    cfg: PriorConfig, batch_size: int, generator: torch.Generator
) -> PriorBatch:
    """Sample a batch of synthetic tasks (on CPU)."""
    g = generator
    n_features = _randint(g, cfg.min_features, cfg.max_features)
    n_rows = _randint(g, cfg.min_rows, cfg.max_rows)
    frac = cfg.min_train_frac + (cfg.max_train_frac - cfg.min_train_frac) * float(
        torch.rand(1, generator=g).item()
    )
    train_size = min(max(int(n_rows * frac), cfg.max_classes), n_rows - 1)

    noise_dim = _randint(g, cfg.min_noise_dim, cfg.max_noise_dim)
    depth = _randint(g, cfg.min_depth, cfg.max_depth)
    widths = [_randint(g, cfg.min_width, cfg.max_width) for _ in range(depth)]
    # ensure the node pool is large enough for n_features + 1 distinct nodes
    widths[0] = max(widths[0], n_features + 1)
    activation = _ACTIVATIONS[_randint(g, 0, len(_ACTIVATIONS) - 1)]

    b, r = batch_size, n_rows
    h = torch.randn(b, r, noise_dim, generator=g)
    gain = torch.exp(torch.randn(b, 1, 1, generator=g) * 0.5)
    nodes = [h]
    for width in widths:
        fan_in = h.shape[-1]
        w = torch.randn(b, fan_in, width, generator=g) * (gain / math.sqrt(fan_in))
        bias = torch.randn(b, 1, width, generator=g) * 0.2
        h = activation(h @ w + bias)
        nodes.append(h)
    pool = torch.cat(nodes, dim=-1)  # (B, R, P)
    pool = (pool - pool.mean(dim=1, keepdim=True)) / (
        pool.std(dim=1, keepdim=True) + 1e-6
    )

    # target node from the deepest layer; feature nodes anywhere else
    n_pool = pool.shape[-1]
    t_idx = n_pool - widths[-1] + torch.randint(widths[-1], (b,), generator=g)
    scores = torch.rand(b, n_pool, generator=g)
    scores.scatter_(1, t_idx.unsqueeze(1), 2.0)  # target never picked as a feature
    f_idx = scores.argsort(dim=1)[:, :n_features]
    x = pool.gather(2, f_idx.unsqueeze(1).expand(b, r, n_features))
    target = pool.gather(2, t_idx.view(b, 1, 1).expand(b, r, 1)).squeeze(-1)

    # rank-bin the target into classes with random per-task proportions
    t = target + 1e-3 * torch.randn(b, r, generator=g)
    ranks = t.argsort(dim=1).argsort(dim=1).float() / (r - 1)
    n_classes = torch.randint(cfg.min_classes, cfg.max_classes + 1, (b,), generator=g)
    props = torch.rand(b, cfg.max_classes, generator=g) + 0.3
    class_mask = torch.arange(cfg.max_classes).unsqueeze(0) < n_classes.unsqueeze(1)
    props = props * class_mask
    props = props / props.sum(dim=1, keepdim=True)
    bounds = props.cumsum(dim=1)[:, :-1]
    bounds = bounds.masked_fill(~class_mask[:, 1:], 2.0)  # unused cuts never trigger
    y = (ranks.unsqueeze(-1) > bounds.unsqueeze(1)).sum(dim=-1)

    # occasional column discretization (before affine; columns are ~N(0,1) here)
    disc = torch.rand(b, 1, n_features, generator=g) < cfg.discretize_prob
    levels = (2.0 + torch.rand(b, 1, n_features, generator=g) * 8.0).floor() / 6.0
    x = torch.where(disc, torch.round(x * levels) / levels.clamp(min=1e-6), x)

    # random per-column affine plus mild observation noise
    scale = torch.exp(torch.randn(b, 1, n_features, generator=g) * 0.7)
    shift = torch.randn(b, 1, n_features, generator=g)
    noise = torch.rand(b, 1, 1, generator=g) * 0.1
    x = x * scale + shift + noise * scale * torch.randn(b, r, n_features, generator=g)

    # per-task MCAR cell missingness
    if cfg.max_cell_missing_frac > 0:
        p_missing = torch.rand(b, 1, 1, generator=g) * cfg.max_cell_missing_frac
        missing = torch.rand(b, r, n_features, generator=g) < p_missing
        x = x.masked_fill(missing, math.nan)

    return PriorBatch(
        x=x, y=y.long(), train_size=train_size, n_classes=n_classes.long()
    )


def apply_cell_missing(
    x: torch.Tensor, prob: torch.Tensor, generator: torch.Generator
) -> torch.Tensor:
    """NaN cells with per-cell probabilities ``prob`` (B, R, F).

    Keeps at least one originally observed cell per row so no row goes fully
    blank.
    """
    mask = torch.rand(x.shape, generator=generator) < prob
    observed = ~torch.isnan(x)
    protect = (torch.rand(x.shape, generator=generator) + observed.float()).argmax(
        dim=-1
    )
    mask.scatter_(-1, protect.unsqueeze(-1), False)
    return x.masked_fill(mask, math.nan)


def random_cell_missing(
    x: torch.Tensor,
    y: torch.Tensor,
    n_classes: torch.Tensor,
    task_prob: float,
    max_rate: float,
    informative_prob: float,
    generator: torch.Generator,
) -> torch.Tensor:
    """Questionnaire-style training augmentation on ALL rows (train and test).

    Per task (with probability ``task_prob``): draw a task mean rate
    u ~ U[0, max_rate], then per-row rates ~ U[0, 2u] — rows differ in
    completeness like survey responses. With probability ``informative_prob``
    the task's missingness is label-informative (MNAR): a random half of the
    columns gets its rate scaled by the row's class rank, so *which cells are
    missing* itself carries signal about the label.
    """
    b, r, f = x.shape
    g = generator
    active = (torch.rand(b, 1, generator=g) < task_prob).float()
    u = torch.rand(b, 1, generator=g) * max_rate
    rates = torch.rand(b, r, generator=g) * 2.0 * u * active
    prob = rates.unsqueeze(-1).expand(b, r, f)
    informative = torch.rand(b, 1, 1, generator=g) < informative_prob
    info_cols = torch.rand(b, 1, f, generator=g) < 0.5
    y_rank = y.float() / (n_classes.view(-1, 1).float() - 1.0).clamp(min=1.0)
    scaled = rates.unsqueeze(-1) * 2.0 * y_rank.unsqueeze(-1)
    prob = torch.where(informative & info_cols, scaled, prob)
    return apply_cell_missing(x, prob.clamp(max=0.95), g)


def sample_dropped_columns(
    batch_size: int, n_features: int, n_drop: torch.Tensor, generator: torch.Generator
) -> torch.Tensor:
    """Boolean mask (B, F) with exactly ``n_drop[b]`` randomly chosen True columns per task."""
    scores = torch.rand(batch_size, n_features, generator=generator)
    col_rank = scores.argsort(dim=1).argsort(dim=1)
    return col_rank < n_drop.unsqueeze(1)


def apply_test_missing(
    x: torch.Tensor, train_size: int, dropped: torch.Tensor
) -> torch.Tensor:
    """NaN out the ``dropped`` (B, F) columns in the test rows only."""
    x = x.clone()
    x[:, train_size:, :] = x[:, train_size:, :].masked_fill(
        dropped.unsqueeze(1), math.nan
    )
    return x


def random_test_missing(
    x: torch.Tensor,
    train_size: int,
    task_prob: float,
    max_drop_frac: float,
    generator: torch.Generator,
) -> torch.Tensor:
    """Training augmentation: per task, drop a random subset of test-row columns.

    With probability ``task_prob`` a task gets between 1 and
    ``floor(F * max_drop_frac)`` (at least 1, at most F - 1) columns NaN'd in
    its test rows; other tasks are left untouched.
    """
    batch_size, _, n_features = x.shape
    if n_features < 2 or task_prob <= 0:
        return x
    max_drop = min(n_features - 1, max(1, int(n_features * max_drop_frac)))
    n_drop = torch.randint(1, max_drop + 1, (batch_size,), generator=generator)
    n_drop = n_drop * (torch.rand(batch_size, generator=generator) < task_prob)
    dropped = sample_dropped_columns(batch_size, n_features, n_drop, generator)
    return apply_test_missing(x, train_size, dropped)
